apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pillplop.postgres.name" . }}
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.container.image }}:{{ .Values.postgres.container.tag }}
        imagePullPolicy: {{ .Values.postgres.container.pullPolicy }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db.name }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.db.password }}
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
          name: postgres
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: postgres-init
          subPath: init.sql
      volumes:
      - name: postgres-init
        configMap:
          name: {{ template "pillplop.postgres.name" . }}-init
