apiVersion: v1
kind: Service
metadata:
  name: {{ template "pillplop.postgres.name" . }}
  labels:
    app: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: postgres
    name: postgres
  selector:
    app: postgres
